#version: "3"
services:
  caddy:
    image: caddy:2.8
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
    
      
  database:
    image: postgis/postgis:13-master
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "monaslyceeuser"
      POSTGRES_PASSWORD_FILE: "/run/secrets/database_password"
      POSTGRES_DB: "monaslyceedb"
    secrets: 
      - database_password

  # cache:
  #   image: redis:6

  directus:
    build: ./directus 
    ports:
      - 8055:8055
    volumes:
      - ./directus/uploads:/directus/uploads
      - ./extensions:/directus/extensions
    depends_on:
      # - cache
      - database
    environment:
      # PUBLIC_URL: "monaslyceeapp.bhdev.org"
      KEY_FILE: '/run/secrets/directus_secret_key'
      SECRET_FILE: '/run/secrets/directus_secret'
      CORS_ENABLED: true
      CORS_ORIGIN: '*'
      WEBSOCKETS_ENABLED: true
      LOG_LEVEL: 'error'

      DB_CLIENT: "pg"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_DATABASE: "monaslyceedb"
      DB_USER: "monaslyceeuser"
      DB_PASSWORD_FILE: '/run/secrets/database_password'

      # CACHE_ENABLED: "true"
      # CACHE_STORE: "redis"
      # REDIS: "redis://cache:6379"

      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD_FILE: "/run/secrets/directus_admin_password"

      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      # PUBLIC_URL: "https://directus.example.com"
    secrets:
      - database_password
      - directus_secret
      - directus_admin_password
      - directus_secret_key
    

    # Environment variables can also be defined in a file (for example `.env`):
    # env_file:
    # - .env
secrets:
  database_password:
    file: ./secrets/database_password.txt
  directus_secret:
    file: ./secrets/directus_secret.txt
  directus_admin_password:
    file: ./secrets/directus_admin_password.txt
  directus_secret_key:
    file: ./secrets/directus_secret_key.txt


